[tool.poetry]
name = "forensic-flow"
version = "1.4.0"
description = "An event-centric, UCO/CASE-compliant ontology framework for IoT digital forensics"
authors = ["Pavel Chikul <pavel.chikul@taltech.ee>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
rdflib = "^7.6.0"
pytz = ">=2026.3"

[tool.poetry.group.dev.dependencies]
pyshacl = "^0.40.1"
